INSERT INTO PUBLISHING_APP VALUES('Telegram')
GO

INSERT INTO WAREHOUSE VALUES('Amazon')
GO

INSERT INTO GENERAL_CONFIGURATION VALUES ('Intervalo de tempo de execução dos itens da fila', 'EXECUTION_TIME_INTERVAL', 5, null)
GO